FORMAT: 1A

# Invitation Service

This is an API micro service for inviting other people to a team.


# Group Invites
## Pending Invites [/invites]
### List pending invites [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Mark Essien",
                "email": "markessien@gmail.com"
            }
            ...
        ]
        

## Send [/invites/send]
### Send an invite [POST]
+ Request (application/json)

        {
            "name": "Mark Essien",
            "email": "markessien@gmail.com"
        }
+ Response 200 (application/json)

        {
                
            "message": "We sent a one use code to markessien@gmail.com"
        }

+ Response 401 (application/json)

        {
            "message": "invalid email"
        }
        
## Verify  [/invites/verify]
### Verify an invite [POST]

+ Request (application/json)

        {
            "email": "markessien@gmail.com",
            "code": "m123e4567-e89b"
        }
        
+ Response 200 (application/json)

        {
                "message": "successfully verified"
                
        }

+ Response 401 (application/json)

        {
            "message": "invalid code"
        }